#!/bin/bash

#git remote add origin zippy.rayservers.com:/home/lisp/git/cl-loom.git
#git remote add ok ok.acotilo.com:/home/lisp/git/cl-loom.git

# get the current branch, "git branch --contains" outputs "* branch"
branch=`git branch --contains`
branch=${branch:2}

echo "Pushing $branch"
git push origin $branch
git push truledger $branch
git push zippy $branch
git push ok $branch
